### ISSUE TITLE
请问Web-UI的密码是哪块位置设置的？

### ISSUE THREAD

**Issue by AulusCaelius** [SinKy-Yan/zhenxunbot-docker#1]
真寻的后台需要用户名和密码，请问如何配置

**Comment by SinKy-Yan** [comment]
是我的疏忽，这两天就会加上自定义用户名和密码的功能👌
现在这个版本使用的是默认账号和密码，账号是`admin`，密码是`123456`，如果你想改可以`exec`进容器去改

**Comment by SinKy-Yan** [comment]
最新版镜像已修复
