### ISSUE TITLE
关于docker-compose.yaml文件中version字段的问题

### ISSUE THREAD

**Issue by BigestMoon** [SinKy-Yan/zhenxunbot-docker#26]
问题描述：
当我clone了项目到本地，改完`docker-compose.yaml`文件之后
运行`docker-compose up -d`命令
出现了如下报错：
`ERROR: Version "2.6.1" in "./docker-compose.yml" is invalid.`

解决办法：
Google之后，看了看docker-compose官方文档之后，上面的大概意思就是版本号和docker引擎得对应
英语不太好，反正我是这么理解的
故此
修改`docker-compose.yaml`文件的第1行：
`version: "2.6.1"`
改为
`version: "3.8"`

之后问题得到了解决，不知道是我的问题，还是配置文件的问题
提出issus，望关注
祝好

**Comment by SinKy-Yan** [comment]
谢谢，这个我有空看看，可能是更新了
