### ISSUE TITLE
webUI设置密码后无法登陆

### ISSUE THREAD

**Issue by KiriharaRi** [SinKy-Yan/zhenxunbot-docker#5]
如题，登录时总是提示未知错误/用户名密码错误，未知错误时logs显示proxy error could not proxy request /webui/login from xxx:8081 to localhost:8080，
提示用户名密码错误的时候就logs就或是提示401或是根本没反应了（

**Comment by KiriharaRi** [comment]
进来了，账号密码改成默认的重启就进来了是不是我设超长了……不懂……

**Comment by SinKy-Yan** [comment]
你这个不知道怎么复现，我先关闭了
