### ISSUE TITLE
更方便的扫描登录

### ISSUE THREAD

**Issue by Jerryjzr** [SinKy-Yan/zhenxunbot-docker#6]
可不可以对go-cqhttp生成的二维码经行一个文件映射，这样可以更容易的扫码登录

**Comment by SinKy-Yan** [comment]
应该可以

**Comment by SinKy-Yan** [comment]
咕咕咕，新版本使用docker compose把运行的东西都分开了，现在gocq的日志可以单独查看，也就是支持方便的扫码登录了
