### ISSUE TITLE
关于webui插件的问题

### ISSUE THREAD

**Issue by Viteyun** [SinKy-Yan/zhenxunbot-docker#8]
别人说是参数数量不对，但是看了一眼，参数数量对的，目前不确定是哪一步会触发这个异常
但是触发后会一直循环提示，导致bot无法继续工作

![M((`JHG$CTGD16`{9V_6ID9](https://user-images.githubusercontent.com/58723716/175885470-74cfcaa5-827b-41e3-a4e1-d81f373f71fe.png)
![F)JF 9$6G6H$9U X9}0L1J8](https://user-images.githubusercontent.com/58723716/175885474-0ad03d5f-8789-4379-8665-8bca95137b05.png)

**Comment by SinKy-Yan** [comment]
这个···只能说不推荐使用webui，bug蛮多的，他们已经打算重写了
