### ISSUE TITLE
bot的插件不起作用

### ISSUE THREAD

**Issue by hyou03** [SinKy-Yan/zhenxunbot-docker#9]
你好，我是unraid系统安装的，
1.go-cqhttp正常登录并连接到反向服务器了，webui也可以正常显示，但是群里发消息后插件不起作用，重启也如此。
2.zhenxun_bot那边支持的插件下载后放到my_plugins文件夹就可以吗？我下载插件放到文件后刷新webui那边也没有显示下载的插件。
感谢。

**Comment by SinKy-Yan** [comment]
1. 你弄的是哪个插件，不起作用的原因有很多：没加载、加载错误、触发了但是执行错误、根本没触发、触发了并且执行成功了但是消息被风控了、插件响应优先级太低
2. 可以，但是新放在`my_plugins`里的插件需要重启bot才能加载，你先看一下容器的启动日志那个插件加载上没有

**Comment by hyou03** [comment]
> 

1. 我刚刚重启后试了一下，插件是 鲁迅说 的插件，第一条有正常发出来图片了，第二条就不行了
![QQ截图20220629203341](https://user-images.githubusercontent.com/76140952/176437997-a5edffaa-f6bf-42ca-9c0e-b4f726f13a01.png)
这个是截图的日志。
2.插件放到文件夹后重启docker在启动日志那边没看到有加载到这个插件，映射的路径应该没有错
不知道是不是改了文件夹名字问题？
![QQ截图20220629203909](https://user-images.githubusercontent.com/76140952/176439064-90e515d9-b193-41af-b0e6-942c9103f050.png)

。

**Comment by hyou03** [comment]
这个就很怪，有时候重启了发好几次插件触发命令 好几次都好使 有时候就不行。
![错误日志](https://user-images.githubusercontent.com/76140952/176445648-6aeb3ae4-df99-4524-b311-7cb3ea7aed7d.png)
1.我前两天装的镜像，应该是最新版，没有更新过。
2.更新插件仓库>查看插件仓库>安装插件3 这三步弄好了，bot提示 成功安装插件 zhenxun_plugin_petpet，请重启真寻！。
重启后也没有诶，正常装上的话应该显示在WebUi那边吧。权限问题吗？

**Comment by SinKy-Yan** [comment]
鲁迅你截一下报错这一大段最下面那里

petpet你进容器去看一下`/home/zhenxun_bot/extensive_plugin`里看看有没有`zhenxun_plugin_petpet`文件夹

![image](https://user-images.githubusercontent.com/56128013/176446778-4ddf74f6-74de-491a-9897-877707156247.png)

或者你直接跟真寻说帮助看看帮助里有没有它,webui不太靠谱

**Comment by hyou03** [comment]
文件夹里面有插件
![QQ截图20220629213659](https://user-images.githubusercontent.com/76140952/176450175-5a087343-b15a-4f68-93db-b033e1612ff5.png)
。

**Comment by SinKy-Yan** [comment]
不知道怎么办了
